-- MySQL Script generated by MySQL Workbench
-- Fri Jun  9 20:25:21 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema sensores
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema sensores
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sensores` DEFAULT CHARACTER SET utf8 ;
USE `sensores` ;

-- -----------------------------------------------------
-- Table `sensores`.`registro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sensores`.`registro` (
  `id_registro` INT NOT NULL,
  `Fecha` VARCHAR(45) NOT NULL,
  `Temperatura` DECIMAL NOT NULL,
  `Humedad` DECIMAL NULL,
  `Presion` DECIMAL NULL,
  PRIMARY KEY (`id_registro`),
  UNIQUE INDEX `fecha_UNIQUE` (`id_registro` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sensores`.`alerta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sensores`.`alerta` (
  `id_alerta` INT NOT NULL,
  `¨Fecha` VARCHAR(45) NOT NULL,
  `id_registro` INT NOT NULL,
  UNIQUE INDEX `id_alerta_UNIQUE` (`id_alerta` ASC) VISIBLE,
  PRIMARY KEY (`id_alerta`, `id_registro`),
  UNIQUE INDEX `¨Fecha_UNIQUE` (`¨Fecha` ASC) VISIBLE,
  INDEX `fk_alerta_registro_idx` (`id_registro` ASC) VISIBLE,
  CONSTRAINT `fk_alerta_registro`
    FOREIGN KEY (`id_registro`)
    REFERENCES `sensores`.`registro` (`id_registro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
